server:
  port: 8189

spring:
  application:
    name: market
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/market?currentSchema=public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

jwt:
  secret: c29rb2xvdg==