server:
  port: 8081
spring:
  application:
    name: product
  flyway:
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: c29rb2xvdg==