server:
  port: 8190

# Настройки базы данных
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/product?currentSchema=public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate